version: "3"

services:
  wordpress:
    image: wordpress:4.9-php5.6-apache
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env

volumes:
  dbdata:
